config/routes.rb
Describe::Application.routes.draw do
  
  resources :notices
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "pages/home"
  get "pages/help"
  get "pages/contact"
  get "pages/about"

  root :to => 'pages#home'

  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="topped">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
		</ul>
  </nav>
	<br/>
	  <%= link_to "de[scribe]", root_path, :class => "mainTitle" %><br/>
		<%= link_to "The Digital School Library Project", root_path, :class => "subTitle" %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
</head>
<body>	
	<div class="container">
		<%= render 'layouts/header' %>
    <section class="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
   </div>
</body>
</html>